### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by imabhishekkumar** [imabhishekkumar/CodeX_Flutter#1]
The UI is very basic, needs improvement

**Comment by uditswaroopa09** [comment]
Hey @imabhishekkumar I can help you please assign it to me

**Comment by imabhishekkumar** [comment]
Sure.

**Comment by uditswaroopa09** [comment]
Hello @imabhishekkumar in Line 202 in home.dart 
filePath = await FilePicker.getFilePath(type: FileType.ANY);
an error is comming 
There's no constant named 'ANY' in 'FileType'.
Try correcting the name to the name of an existing constant, or defining a constant named 'ANY'
Can you please explain why I am getting that??
![image](https://user-images.githubusercontent.com/65483816/94777546-42500f00-03e1-11eb-93fc-e8ab515ae9bc.png)

**Comment by imabhishekkumar** [comment]
Hi, the project was made 2 years ago using the latest libraries available back then. Since then there are many changes in Flutter SDK. They must have changed the FilePicker library.  
Try changing FileType.ANY to FileType.any

**Comment by uditswaroopa09** [comment]
sure I have replaced the getFile method with the print("Add Get File Here") I hope you will change after the PR, 
btw I am in dev channel so your thoughts are correct

**Comment by imabhishekkumar** [comment]
Okay.
